"""Add mentions relationship to Comment

Revision ID: 37898715e0f0
Revises: 5fd3e66672b4
Create Date: 2025-09-18 13:06:21.025439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37898715e0f0'
down_revision: Union[str, Sequence[str], None] = '5fd3e66672b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
