"""Migrate bookmarking from Report to Post

Revision ID: 3ae303d284a2
Revises: 958f797d469f
Create Date: 2025-09-19 01:34:50.646605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae303d284a2'
down_revision: Union[str, Sequence[str], None] = '958f797d469f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarked_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarked_reports',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('bookmarked_reports_report_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookmarked_reports_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'report_id', name=op.f('bookmarked_reports_pkey'))
    )
    # ### end Alembic commands ###
