"""Add hash_tag to posts

Revision ID: 42a25ac7a654
Revises: 7d9faa17a38b
Create Date: 2025-09-18 05:41:47.882138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a25ac7a654'
down_revision: Union[str, Sequence[str], None] = '7d9faa17a38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('hash_tag', sa.ARRAY(sa.String(length=10)), nullable=True))
    op.add_column('posts', sa.Column('public', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('posts', sa.Column('speed', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('distance', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'time')
    op.drop_column('posts', 'distance')
    op.drop_column('posts', 'speed')
    op.drop_column('posts', 'public')
    op.drop_column('posts', 'hash_tag')
    # ### end Alembic commands ###
