"""Add fcm_token and fcm_token_updated_at to User

Revision ID: 4ebc019523f0
Revises: dc77690160da
Create Date: 2025-09-18 12:19:22.066949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebc019523f0'
down_revision: Union[str, Sequence[str], None] = 'dc77690160da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('fcm_token_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'fcm_token_updated_at')
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###
