"""Add map_image_url to Post model

Revision ID: 65403aa777d7
Revises: 9129176846e6
Create Date: 2025-09-19 16:00:42.643962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65403aa777d7'
down_revision: Union[str, Sequence[str], None] = '9129176846e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarked_routes')
    op.add_column('posts', sa.Column('map_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'map_image_url')
    op.create_table('bookmarked_routes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('bookmarked_routes_route_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookmarked_routes_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'route_id', name=op.f('bookmarked_routes_pkey'))
    )
    # ### end Alembic commands ###
