"""Change health_time and half_time to Integer in Report model

Revision ID: 78d18dbc1bd5
Revises: 8485f0ed9ac5
Create Date: 2025-09-15 12:49:26.125437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78d18dbc1bd5'
down_revision: Union[str, Sequence[str], None] = '8485f0ed9ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'health_time')
    op.add_column('reports', sa.Column('health_time', sa.Integer(), nullable=True, server_default='0'))
    op.drop_column('reports', 'half_time')
    op.add_column('reports', sa.Column('half_time', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'half_time')
    op.add_column('reports', sa.Column('half_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'health_time')
    op.add_column('reports', sa.Column('health_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
