"""Add route_id to Report model and establish relationship

Revision ID: 8485f0ed9ac5
Revises: c0d0c51001f0
Create Date: 2025-09-15 12:23:39.594177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8485f0ed9ac5'
down_revision: Union[str, Sequence[str], None] = 'c0d0c51001f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('route_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'routes', ['route_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'route_id')
    # ### end Alembic commands ###
