"""add start and end points to route model

Revision ID: 88c336cf0ae4
Revises: d791462e4aa6
Create Date: 2025-09-16 14:55:17.205416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c336cf0ae4'
down_revision: Union[str, Sequence[str], None] = 'd791462e4aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('start_point', sa.String(), nullable=True))
    op.add_column('routes', sa.Column('end_point', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'end_point')
    op.drop_column('routes', 'start_point')
    # ### end Alembic commands ###
