"""Migrate bookmarking from Route to Report

Revision ID: 958f797d469f
Revises: a6a6f8f1db17
Create Date: 2025-09-19 01:29:31.197999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958f797d469f'
down_revision: Union[str, Sequence[str], None] = 'a6a6f8f1db17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarked_routes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarked_routes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('bookmarked_routes_route_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookmarked_routes_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'route_id', name=op.f('bookmarked_routes_pkey'))
    )
    # ### end Alembic commands ###
