"""Add ondelete=CASCADE to comment foreign keys in notifications and mentions

Revision ID: a4c4b427af6c
Revises: 166b8dbd3c06
Create Date: 2025-09-30 22:55:37.956787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c4b427af6c'
down_revision: Union[str, Sequence[str], None] = '166b8dbd3c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('mentions_comment_id_fkey'), 'mentions', type_='foreignkey')
    op.create_foreign_key(None, 'mentions', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notifications_comment_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_comment_id_fkey'), 'notifications', 'comments', ['comment_id'], ['id'])
    op.drop_constraint(None, 'mentions', type_='foreignkey')
    op.create_foreign_key(op.f('mentions_comment_id_fkey'), 'mentions', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
