"""Add route_id to Post model and establish relationship

Revision ID: a51eb4ff54e7
Revises: 78d18dbc1bd5
Create Date: 2025-09-15 13:30:27.642898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51eb4ff54e7'
down_revision: Union[str, Sequence[str], None] = '78d18dbc1bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('route_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'routes', ['route_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'route_id')
    # ### end Alembic commands ###
