"""Add like_count to Comment model

Revision ID: a6a6f8f1db17
Revises: 90c2ef11529f
Create Date: 2025-09-19 01:23:45.215594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a6f8f1db17'
down_revision: Union[str, Sequence[str], None] = '90c2ef11529f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'like_count')
    # ### end Alembic commands ###
