"""Fix model relationships

Revision ID: c0d0c51001f0
Revises: 94b3656b8cb7
Create Date: 2025-09-15 11:01:13.983793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d0c51001f0'
down_revision: Union[str, Sequence[str], None] = '94b3656b8cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'routes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_column('routes', 'user_id')
    # ### end Alembic commands ###
