"""Make profile_description in User model nullable

Revision ID: d791462e4aa6
Revises: 8141ca6f2664
Create Date: 2025-09-16 11:57:13.588488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd791462e4aa6'
down_revision: Union[str, Sequence[str], None] = '8141ca6f2664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
