"""Link post to report instead of route

Revision ID: dc77690160da
Revises: 42a25ac7a654
Create Date: 2025-09-18 09:40:13.725529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc77690160da'
down_revision: Union[str, Sequence[str], None] = '42a25ac7a654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('report_id', sa.Integer(), nullable=True))
    op.alter_column('posts', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('posts_route_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'reports', ['report_id'], ['id'])
    op.drop_column('posts', 'route_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_route_id_fkey'), 'posts', 'routes', ['route_id'], ['id'])
    op.alter_column('posts', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('posts', 'report_id')
    # ### end Alembic commands ###
