"""Add subscription fields to user model

Revision ID: fb3692856c75
Revises: 14d7054a2c22
Create Date: 2025-11-15 21:53:31.882979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb3692856c75'
down_revision: Union[str, Sequence[str], None] = '14d7054a2c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stamps')
    op.add_column('users', sa.Column('is_subscribed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('subscription_expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('google_purchase_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_purchase_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_purchase_token')
    op.drop_column('users', 'subscription_expiry_date')
    op.drop_column('users', 'is_subscribed')
    op.create_table('Stamps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stamp_lev', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('Stamps_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Stamps_pkey'))
    )
    # ### end Alembic commands ###
